
/**
 * Datos de prueba para la colección de libros.
 */

export const libros = [
   {
      isbn: '9763161484100',
      titulo: 'Cien años de soledad',
      autor: 'Gabriel García Márquez',
      fechaPub: '1967-05-30',
      resumen:
         'La historia de la familia Buendía en el pueblo ficticio de Macondo.',
      genero: 'Realismo mágico',
      stock: 5,
      precio: 35.59,
      fechaCompra: '2025-01-17',
   },
   {
      isbn: '9768437604947',
      titulo: 'Don Quijote de la Mancha',
      autor: 'Miguel de Cervantes',
      fechaPub: '1605-01-16',
      resumen:
         'Las aventuras de un hidalgo obsesionado con los libros de caballería.',
      genero: 'Clásico',
      stock: 3,
      precio: 20.15,
      fechaCompra: '2025-01-16',
   },
   {
      isbn: '9768420483001',
      titulo: 'La sombra del viento',
      autor: 'Carlos Ruiz Zafón',
      fechaPub: '2001-04-17',
      resumen: 'Un joven descubre un libro maldito que cambiará su vida.',
      genero: 'Misterio',
      stock: 2,
      precio: 12.19,
      fechaCompra: '2025-01-17',
   },
   {
      isbn: '9768490664393',
      titulo: 'El amor en los tiempos del cólera',
      autor: 'Gabriel García Márquez',
      fechaPub: '1985-09-05',
      resumen: 'Una historia de amor que trasciende el tiempo.',
      genero: 'Romance',
      stock: 1,
      precio: 57.30,
      fechaCompra: '2025-01-20',
   },
   {
      isbn: '9768432234674',
      titulo: 'El alquimista',
      autor: 'Paulo Coelho',
      fechaPub: '1988-11-01',
      resumen: 'Un pastor busca su leyenda personal.',
      genero: 'Filosofía',
      stock: 1,
      precio: 15.00,
      fechaCompra: '2025-01-18',
   },
   {
      isbn: '9768426482260',
      titulo: 'Rayuela',
      autor: 'Julio Cortázar',
      fechaPub: '1963-06-28',
      resumen: 'Una novela innovadora que desafía la narrativa tradicional.',
      genero: 'Experimental',
      stock: 2,
      precio: 80.59,
      fechaCompra: '2025-01-20',
   },
   {
      isbn: '9768437502417',
      titulo: 'Pedro Páramo',
      autor: 'Juan Rulfo',
      fechaPub: '1955-01-01',
      resumen: 'Un viaje a Comala en busca de un padre desconocido.',
      genero: 'Realismo mágico',
      stock: 3,
      precio: 25.99,
      fechaCompra: '2025-01-16',
   },
   {
      isbn: '9768420681944',
      titulo: 'La casa de los espíritus',
      autor: 'Isabel Allende',
      fechaPub: '1982-01-01',
      resumen: 'La saga de una familia llena de amor, política y tragedia.',
      genero: 'Realismo mágico',
      stock: 4,
      precio: 61.23,
      fechaCompra: '2025-01-17',
   },
   {
      isbn: '9768493807672',
      titulo: 'Crónica de una muerte anunciada',
      autor: 'Gabriel García Márquez',
      fechaPub: '1981-01-01',
      resumen: 'El relato del asesinato anunciado de Santiago Nasar.',
      genero: 'Crimen',
      stock: 1,
      precio: 45.52,
      fechaCompra: '2025-01-12',
   },
   {
      isbn: '9768497932542',
      titulo: 'Los renglones torcidos de Dios',
      autor: 'Torcuato Luca de Tena',
      fechaPub: '1979-01-01',
      resumen:
         'Una mujer se interna en un hospital psiquiátrico para resolver un crimen.',
      genero: 'Thriller',
      stock: 2,
      precio: 55.05,
      fechaCompra: '2025-01-22',
   },
];

/**
 * Datos de prueba para la colección de usuarios.
 */
export const usuarios = [
   {
      email: 'usuario1@viu.es',
      nombre: 'Juan',
      apellido1: 'García',
      apellido2: 'Pérez',
   },
   {
      email: 'usuario2@viu.es',
      nombre: 'María',
      apellido1: 'Martínez',
      apellido2: 'López',
   },
   {
      email: 'usuario3@viu.es',
      nombre: 'Pedro',
      apellido1: 'Fernández',
      apellido2: 'Gómez',
   },
   {
      email: 'usuario4@viu.es',
      nombre: 'Carmen',
      apellido1: 'Sánchez',
      apellido2: 'Rodríguez',
   },
   {
      email: 'usuario5@viu.es',
      nombre: 'Luis',
      apellido1: 'Hernández',
      apellido2: 'Díaz',
   },
   {
      email: 'usuario6@viu.es',
      nombre: 'Ana',
      apellido1: 'Ruiz',
      apellido2: 'Morales',
   },
   {
      email: 'usuario7@viu.es',
      nombre: 'Miguel',
      apellido1: 'Jiménez',
      apellido2: 'Ortiz',
   },
   {
      email: 'usuario8@viu.es',
      nombre: 'Laura',
      apellido1: 'González',
      apellido2: 'Navarro',
   },
   {
      email: 'usuario9@viu.es',
      nombre: 'José',
      apellido1: 'Ramos',
      apellido2: 'Iglesias',
   },
   {
      email: 'usuario10@viu.es',
      nombre: 'Elena',
      apellido1: 'Torres',
      apellido2: 'Castro',
   },
];
